name: Deploy on EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml

    - name: EC2 Deploy Action
      run: |
           echo "${{secrets.KEY_EC2}}" > springKey && chmod 400 springKey
           ssh -o StrictHostKeyChecking=no -i "springKey" ubuntu@ec2-44-199-0-95.compute-1.amazonaws.com "
             cd /home/ubuntu/POC &&
             git pull &&
             mvn clean package -DskipTests &&
             ./execute.sh"
